name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.0.0
    - name: Restore dependencies
      run: dotnet restore ./TopDownShooter/TopDownShooter.sln
    - name: Build
      run: dotnet build --no-restore ./TopDownShooter/TopDownShooter.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./TopDownShooter/TopDownShooter.sln
